# Configuration file
# Parameters that exist both on config and cmdline will have cmdline as preference

bind:
  #address: ":8080"
  #network: "tcp"
  #socket-mode": "0770"

  # Enable PROXY mode on this listener, to allow passing origin info. Default false
  #proxy: true

  # Enable passthrough mode, which will allow traffic onto the backends while rules load. Default false
  #passthrough: true

  # Enable TLS on this listener and obtain certificates via an ACME directory URL, or letsencrypt
  #tls-acme-autocert: "letsencrypt"

  # Enable TLS on this listener and obtain certificates via a certificate and key file on disk
  # Only set one of tls-acme-autocert or tls-certificate+tls-key
  #tls-certificate: ""
  #tls-key: ""

# Bind the Go debug port
#bind-debug: ":6060"

# Bind the Prometheus metrics onto /metrics path on this port
#bind-metrics ":9090"

# These links will be shown on the presented challenge or error pages
links:
  #- name: Privacy
  #  url: "/privacy.html"

  #- name: Contact
  #  url: "mailto:admin@example.com"

  #- name: Donations
  #  url: "https://donations.example.com/abcd"

# HTML Template to use for challenge or error pages
# External templates can be included by providing a disk path
# Bundled templates:
#  anubis: An Anubis-like template with no configuration parameters. Supports Logo.
#  forgejo: Looks like native Forgejo. Includes logos and resources from your instance. Supports Theme, Logo.
#
challenge-template: "mansmarthome"

# Allows overriding specific settings set on templates. Key-Values will be passed to templates as-is
challenge-template-overrides:
  # Logo: "https://cdn.your.website/favicon.png"
  # Favicon: "https://cdn.your.website/favicon.svg"
  Brand: "man smart-home"

# Advanced backend configuration
# Backends setup via cmdline will be added here
backends:
  # Example HTTP backend and setting client ip header
  #"git.example.com":
  #  url: "http://forgejo:3000"
  #  ip-header: "X-Client-Ip"

  # Example HTTP backend matching a non-standard port in Host
  # Standard ports are 80 and 443. Others will be sent in Host by browsers
  #"git.example.com:8080":
  #  url: "http://forgejo:3000"
  #  ip-header: "X-Client-Ip"


  # Example HTTPS backend with host/SNI override, HTTP/2 and no certificate verification
  #"ssl.example.com":
  #  url: "https://127.0.0.1:8443"
  #  host: ssl.example.com
  #  http2-enabled: true
  #  tls-skip-verify: true

  # Example HTTPS transparent backend with host/SNI override, HTTP/2, and subdirectory
  #"ssl.example.com":
  #  url: "https://ssl.example.com/subdirectory/"
  #  host: ssl.example.com
  #  http2-enabled: true
  #  ip-header: "-"
  #  transparent: true

# List of strings you can replace to alter the presentation on challenge/error templates
# Can use other languages.
# Note raw HTML is allowed, be careful with it.
# Default strings exist in code, uncomment any to set it
strings:
  title_challenge: "Требуется подтверждение"
  title_error: "Ошибка:"
  noscript_warning: >
    <p>Для прохождения проверки безопасности требуется включить JavaScript в вашем браузере.</p>
    <p>Это стандартное требование для защиты от автоматических программ и обеспечения работы страницы.</p>
  details_title: "Пожалуйста, подтвердите, что вы не робот.<br>Это необходимо для защиты сайта."
  details_text: >
    <p>Наша система безопасности обнаружила необычную активность, которая может быть связана с автоматическими запросами.</p>
    <p>Эта проверка помогает защитить сайт от перегрузки и обеспечивает его стабильную работу для всех посетителей.</p>
    <p>Для работы проверки требуется JavaScript. Если у вас возникают проблемы, попробуйте:</p>
    <ul>
      <li>Обновить страницу</li>
      <li>Временно отключить блокировщики JavaScript или антитрекинги</li>
      <li>Проверить настройки расширений браузера (например, JShelter, uBlock Origin и подобные)</li>
    </ul>
  details_contact_admin_with_request_id: "Если проблема повторяется, обратитесь к администратору и сообщите идентификатор запроса:"
  button_refresh_page: "Обновить страницу и повторить"
  status_loading_challenge: "Подготовка проверки"
  status_starting_challenge: "Запуск проверки безопасности..."
  status_loading: "Загрузка..."
  status_calculating: "Анализ параметров браузера..."
  status_challenge_success: "Проверка пройдена!"
  status_challenge_done_took: "Время:"
  status_error: "Не удалось завершить проверку:"
